apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: guance-chatbot
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: guance-chatbot
  labels:
    app: redis
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: pubrepo.jiagouyun.com/dataflux-func/redis:5.0.7
        imagePullPolicy: IfNotPresent
        command: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)"]
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: chatbot-env
                key: REDIS_PASSWORD
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
        ports:
          - containerPort: 6379
            name: port
            protocol: TCP
        resources:
          requests:
            cpu: "200m"
            memory: "128Mi"
          limits:
            cpu: "4000m"
            memory: "4Gi"
        volumeMounts:
        - name: redis-data
          mountPath: /data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
