apiVersion: v1
kind: Service
metadata:
  name: weaviate
  namespace: guance-chatbot
spec:
  type: ClusterIP
  selector:
    app: weaviate
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: weaviate
  name: weaviate
  namespace: guance-chatbot
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: weaviate
  template:
    metadata:
      labels:
        app: weaviate
    spec:
      containers:
      - name: weaviate
        image: pubrepo.jiagouyun.com/chatbot/weaviate:1.19.0
        imagePullPolicy: IfNotPresent
        env:
          - name: PERSISTENCE_DATA_PATH
            value: /var/lib/weaviate
          - name: QUERY_DEFAULTS_LIMIT
            value: "25"
          - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
            value: "false"
          - name: DEFAULT_VECTORIZER_MODULE
            value: none
          - name: CLUSTER_HOSTNAME
            value: clust_hostname_xxxx
          - name: AUTHENTICATION_APIKEY_ENABLED
            value: "true"
          - name: AUTHENTICATION_APIKEY_ALLOWED_KEYS
            valueFrom:
              configMapKeyRef:
                name: chatbot-env
                key: WEAVIATE_AUTHENTICATION_APIKEY
          - name: AUTHENTICATION_APIKEY_USERS
            value: hello@dify.ai
          - name: AUTHORIZATION_ADMINLIST_ENABLED
            value: "true"
          - name: AUTHORIZATION_ADMINLIST_USERS
            value: hello@dify.ai
        ports:
          - containerPort: 8080
            name: port
            protocol: TCP
        resources:
          requests:
            cpu: "200m"
            memory: "128Mi"
          limits:
            cpu: "4000m"
            memory: "8Gi"
        securityContext:
          privileged: false
        volumeMounts:
        - name: weaviate-data
          mountPath: /var/lib/weaviate
      dnsPolicy: ClusterFirst
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: weaviate-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi